name: Upload release assets

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  
jobs:
  upload-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace Version.txt URL
        run: |
          sed -i 's|"https://raw.githubusercontent.com/flopp999/Scriptable-Growatt/main/Version.txt"|"https://github.com/flopp999/Scriptable-Growatt/releases/latest/download/Version.txt"|g' Growatt.js

      - name: Replace Growatt.js URL
        run: |
          sed -i 's|"https://raw.githubusercontent.com/flopp999/Scriptable-Growatt/main/Growatt.js"|"https://github.com/flopp999/Scriptable-Growatt/releases/latest/download/Growatt.js"|g' Growatt.js

      - name: Replace Translations.json URL
        run: |
          sed -i 's|"https://raw.githubusercontent.com/flopp999/Scriptable-Growatt/main/Translations.json"|"https://github.com/flopp999/Scriptable-Growatt/releases/latest/download/Translations.json"|g' Growatt.js

      - name: Upload assets to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Growatt.js
            Translations.json
            Version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
